### ISSUE TITLE
DIY Rainbow Light Tube

### ISSUE THREAD

**Issue by teenage-witch** [sibbyandjuju/site#32]
this tutorial https://www.youtube.com/watch?v=RNggWvyPyi4

**Comment by tarngerine** [comment]
To buy:
- [ ] Tube (8' or 4' base?) https://www.homedepot.com/p/Lithonia-Lighting-8-ft-Fluorescent-Tube-Protector-TGT12CL8-R24/100173242
- [x] Lights — use Sabrina's extra light
- [ ] New adapter + controller (~$20)
- [ ] Parchment paper blank

**Comment by tarngerine** [comment]
Done!
