### ISSUE TITLE
Buy asian snacks

### ISSUE THREAD

**Issue by teenage-witch** [sibbyandjuju/site#35]
Doesn't need to be literally everything on this list, these are just ideas

- Assortment of Pocky, especially classic flavors like Strawberry & Chocolate
- Hello Panda
- Shrimp Crackers
- Yakult?
- Spicy Dried Squid
- Pineapple cake?
- Milkita Candy
- White Rabbit Candy
- Nori
- https://www.hmart.com/3114621200
- https://www.hmart.com/8801062144815
- Yan Yan
- Pretz
- Hi-Chews
- Kasugai Gummy Candy
- Rice Crackers

**Comment by tarngerine** [comment]
!close
