### ISSUE TITLE
Amritha Get Ordained

### ISSUE THREAD

**Issue by teenage-witch** [sibbyandjuju/site#6]
https://www.theknot.com/content/friend-officiate-ceremony-how-to

Marraige License: https://www.tarrantcounty.com/en/county-clerk/vital-records/marriage-licenses.html

**Comment by tarngerine** [comment]
Will need to do additional research to confirm legitimacy (esp in Texas), but online ordination through American Fellowship Church or Universal Life Church seem to be the most popular

https://www.amfellow.org/texas-minister-license/
https://getordained.org/state-marriage-laws/texas

Knot article: https://www.theknot.com/content/friend-officiate-ceremony-how-to

We live at the border of Tarrant County and Dallas County, and thus can work with clerks on either side. Closest County Clerk is in Hurst (Tarrant County)

**Comment by tarngerine** [comment]
ULC does ~ seem ~ to be legit and is free https://en.wikipedia.org/wiki/Legal_status_of_the_Universal_Life_Church#Texas

**Comment by tarngerine** [comment]
altho theres like multiple ULC websites https://www.ulc.org/wedding-laws/texas

**Comment by tarngerine** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1629901/69026739-c2b87d80-0991-11ea-948a-4f3e9443b7d8.png">
i cant
