### ISSUE TITLE
Build out R.S.V.P form for Wedding Site

### ISSUE THREAD

**Issue by teenage-witch** [sibbyandjuju/site#7]
Part of Issue #3 

### Design
- [ ] Form submitted state
- [x] Form error state
- [ ] Mobile view (background looks weird right now)

**Comment by tarngerine** [comment]
quick pass at submitted state, but prob need to do a second pass @teenage-witch 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/1629901/69290977-4f984c80-0bc7-11ea-9d93-e34fd997ea56.png">

**Comment by tarngerine** [comment]
So the process we'll have for receiving RSVP is as follows:
1. when someone submits the form, it'll send it to Webflow's form database
2. Webflow will then relay an email to hi@sibbyandjuju.com (see below)
3. Then we manually update the google sheet (linked in email), and we should also have a template to reply to them to confirm the RSVP (we should confirm if they've paid deposit, etc)

<img width="556" alt="image" src="https://user-images.githubusercontent.com/1629901/69030470-4fb50400-099d-11ea-9a98-8237d3e21f95.png">

**Comment by tarngerine** [comment]
Created a template for confirmation in Zoho mail: 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1629901/69030747-103ae780-099e-11ea-9ac5-cf83e2d9098f.png">

To use it, go to mail.zoho.com, click on "Templates" in the left sidebar (under Drafts), and click on the template — it'll create a blank email.

**Comment by tarngerine** [comment]
Made one for attending vs one for not attending. Zoho doesn't let you edit templates, so have to create a new one each time Q_Q

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1629901/69030936-84758b00-099e-11ea-9977-8a7d977bad86.png">

**Comment by tarngerine** [comment]
added error state, a fixed message at the bottom of the screen

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1629901/69290686-53779f00-0bc6-11ea-9ea3-34844d9b8c6a.png">

need to make the background better on mobile tho, and the section headers dont read great bc of text wrapping (e.g. dietary restrictions) "ITS DIETARY RESTRICTIONS" @teenage-witch

**Comment by tarngerine** [comment]
lol "I THINK @ THE EMERSON"
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1629901/69290724-71450400-0bc6-11ea-8c78-5d6455ca23cf.png">

**Comment by tarngerine** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/1629901/69290739-802bb680-0bc6-11ea-8700-25bb2fc73f0e.png">
dope shirt design BE TRANSPORTATION

**Comment by tarngerine** [comment]
changed the arrow to not be tall arrows. other choice is this flatter triangle
<img width="435" alt="image" src="https://user-images.githubusercontent.com/1629901/69290861-e44e7a80-0bc6-11ea-8d90-17e8268559c3.png">
