### ISSUE TITLE
Custom CSS for R.S.V.P. Form

### ISSUE THREAD

**Issue by teenage-witch** [sibbyandjuju/site#8]
Extension of issue #7 

- [x] Change color for Yes/No RSVP selection
- [x] Create red 1px outline (no inner shadow) for Dietary checkboxes
- [x] Create conditional form where 1 person No RSVP disables the rest of the form and they are able to submit w/o answering transportation question.

**Comment by tarngerine** [comment]
all done!

**Comment by tarngerine** [comment]
u can test here:
https://sibby-juju-6333f37c42026e45a36ebaf578ab.webflow.io/rsvp/phan

havent tested on mobile yet
